site_name: akari-notes

nav:
  - 首页:
    - 首页: index.md
  - 算法:
    - Morris Traversal: algo/morris.md
  - 组合数学:
    - 组合数学: comb/index.md
  - 密码学:
    - 密码学: crypto/index.md
    - 古典密码学:
      - 简介: crypto/classical/index.md
    - 格密码学:
      - 简介: crypto/lattice/index.md
      - LLL 算法: crypto/lattice/lll.md
      - Coppersmith 法: crypto/lattice/coppersmith.md

# Theme
theme:
  name: material
  language: zh
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: deep purple
      accent: red
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: blue
      accent: blue
      toggle:
        icon: material/weather-night
        name: Switch to light mode
  icon:
    logo: 'material/school'
  features:
    - navigation.tabs
    - navigation.instant
    - content.code.copy
    - content.code.select
    # - content.code.annotate
  font:
    text: 'Fira Sans'
    code: 'Fira Mono'

markdown_extensions:
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.arithmatex:
      generic: true
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences


extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
